const Type = {
  INT: "int",
  FLOAT: "float",
  BOOL: "bool",
  ERROR: "error",
};

const Operation = {
  ADD: "+",
  SUB: "-",
  MUL: "*",
  DIV: "/",
  ASSIGN: "=",
  NOT_EQUAL: "!=",
  GREATER: ">",
  LESS: "<",
};

const semanticCube = {
  [Type.INT]: {
    [Type.INT]: {
      [Operation.ADD]: Type.INT,
      [Operation.SUB]: Type.INT,
      [Operation.MUL]: Type.INT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.INT,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
    [Type.FLOAT]: {
      [Operation.ADD]: Type.FLOAT,
      [Operation.SUB]: Type.FLOAT,
      [Operation.MUL]: Type.FLOAT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.ERROR,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
    [Type.BOOL]: {
      [Operation.ADD]: Type.INT,
      [Operation.SUB]: Type.INT,
      [Operation.MUL]: Type.INT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.ERROR,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
  },
  [Type.FLOAT]: {
    [Type.INT]: {
      [Operation.ADD]: Type.FLOAT,
      [Operation.SUB]: Type.FLOAT,
      [Operation.MUL]: Type.FLOAT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.ERROR,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
    [Type.FLOAT]: {
      [Operation.ADD]: Type.FLOAT,
      [Operation.SUB]: Type.FLOAT,
      [Operation.MUL]: Type.FLOAT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.FLOAT,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
    [Type.BOOL]: {
      [Operation.ADD]: Type.FLOAT,
      [Operation.SUB]: Type.FLOAT,
      [Operation.MUL]: Type.FLOAT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.ERROR,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
  },
  [Type.BOOL]: {
    [Type.INT]: {
      [Operation.ADD]: Type.INT,
      [Operation.SUB]: Type.INT,
      [Operation.MUL]: Type.INT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.ERROR,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
    [Type.FLOAT]: {
      [Operation.ADD]: Type.FLOAT,
      [Operation.SUB]: Type.FLOAT,
      [Operation.MUL]: Type.FLOAT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.ERROR,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
    [Type.BOOL]: {
      [Operation.ADD]: Type.INT,
      [Operation.SUB]: Type.INT,
      [Operation.MUL]: Type.INT,
      [Operation.DIV]: Type.FLOAT,
      [Operation.ASSIGN]: Type.BOOL,
      [Operation.NOT_EQUAL]: Type.BOOL,
      [Operation.GREATER]: Type.BOOL,
      [Operation.LESS]: Type.BOOL,
    },
  },
};
